[package]
name = "adawolfs/donut"
version = "0.0.2"
description = "This is a port of a1k0n donut.c to WebAssembly"
license = "MIT"
readme = "./README.md"
repository = "https://github.com/adawolfs/wasm-donut"
homepage = "https://wasmer.io/"

[[module]]
name = "donut"
source = "./donut.wasm"
abi = "wasi"

[[command]]
name = "donut"
module = "donut"
